#+title:      My Weekly
#+date:       [2024-12-10 Tue 10:37]
#+filetags:   :post:
#+identifier: 20241210T103716


** Walrus operator

Python 3.8 引入的一种新的赋值表达式，允许在表达式中间对变量进行赋值，帮助开发人员写出更加简单易读可维护的代码。关于其更多的细节可以看这篇文章 ([[https://realpython.com/python-walrus-operator/][The Walrus Operator: Python's Assignment Expressions]])，其中详细的讲解了引入 walrus operator 的初衷和目的，以及应该在何时使用的一些最佳实践。


** Rounding Strategies

这篇文章 ([[elfeed:www.planetpython.org#https://realpython.com/python-rounding/][Real Python: How to Round Numbers in Python]]) 介绍了 Python 生态中的各种 ~round~ 算法以及其最佳实践。第一次了解到 round 的原来还有这么多门道，我想这应该是每一位数据科学家都应该了解的，尤其是 ~rounding bias~ 的概念。


** Learning Vector Quantization

LVQ is a prototype-based supervised classification algorithm.

算法细节参考这篇文章 ([[https://medium.com/@udbhavkush4/demystifying-learning-vector-quantization-a-step-by-step-guide-with-code-implementation-from-ea3c4ab5330e][Learning Vector Quantization (LVQ): A Step-by-Step Guide with Code Implementation from Scratch]]) 。 


** Expression vs Statement

这篇文章 ([[elfeed:www.planetpython.org#https://realpython.com/python-expression-vs-statement/][Real Python: Expression vs Statement in Python: What's the Difference?]]) 总结了 Python 语言中的表达式与语句的区别：

#+begin_quote
In Short: Expressions Have Values and Statements Cause Side Effects.
#+end_quote

从技术的角度来说，在 Python 语言中的每一行每一块代码都是语句 (statement)。表达式 (expressions) 可以看作一种特殊的有值的语句 (statements with values)，本质上，你可以用该计算出来的值替换原表达式而不会改变程序的整体行为。


** TruLens

TruLens is a software tool that helps you to objectively measure the quality and effectiveness of your LLM-based applications using feedback functions.

该工具是我在阅读这篇文章 ([[elfeed:towardsdatascience.com#https://medium.com/p/3c518af836ce][From Retrieval to Intelligence: Exploring RAG, Agent+RAG, and Evaluation with TruLens]]) 时知道的。LLMs App 开发不可或缺的工具。这篇文章也非常有趣，主要介绍如何用 LlamaIndex 框架实现 RAG 。 


** EndeavourOS

EndeavourOS 是一个基于 Arch Linux 的轻量的 Linux 发型版。它的以下几点特性有比较吸引我：

1. 基于 Arch ，与 Arch 使用相同的软件仓库，滚动升级。
2. 用户友好的安装和可供选择的桌面以及，提供了 Calamares 安装程序。
3. 只安装必要的软件包以获得完整的桌面体验，几乎可以获得原生的 Arch 体验。

等候选自己安定下来后，可以用这个 Linux 发行版来搭建工作环境。


** CrewAI

一个 AI Agent 框架，下面是其官网简介：

#+begin_quote
CrewAI: Cutting-edge framework for orchestrating role-playing, autonomous AI agents. By fostering collaborative intelligence, CrewAI empowers agents to work together seamlessly, tackling complex tasks.
#+end_quote


** Gephi

一个开源的图可视化分析软件，可用在 Exploratory Data Analysis, Link Analysis, Social Network Analysis, Biological Network analysis 等方面。下面是其官网简介：

#+begin_quote
Gephi is the leading visualization and exploration software for all kinds of graphs and networks. The goal is to help data analysts to make hypothesis, intuitively discover patterns, isolate structure singularities or faults during data sourcing.
#+end_quote


** NetworkX

一个关于复杂网络的 Python 库，下面是官网简介：

#+begin_quote
NetworkX is a Python package for the creation, manipulation, and study of the structure, dynamics, and functions of complex networks.
#+end_quote


** [[elfeed:towardsdatascience.com#https://medium.com/p/89a9b3a5ad9e][Smaller is Smarter]]

这篇文章指出 LLMs 训练推断上巨大的成本。以 Llama 3.1 405B 为例，就耗电这一项来说，就需要 11GWh ，大概等于法国 4782 个人的平均用电量。其实并不是所有任务都需要大语言模型，小型的语言模型在简单的任务上表现也相当不错。比如作者推荐的 Mistral 7B, Llama-3.2 3B 和 Phi3.5 等。


** Polars: Blazingly fast DataFrames

官网的简介：

#+begin_quote
Polars is a DataFrame interface on top of an OLAP Query Engine implemented in Rust using Apache Arrow Columnar Format as the memory model.
#+end_quote

其主打的是性能，可以作为 Pandas 的替代品。


** Open Food Facts AI Project

这篇文章 ([[elfeed:towardsdatascience.com#https://medium.com/p/d74dfe02e0e4][How Did Open Food Facts Fix OCR-Extracted Ingredients Using Open-Source LLMs?]]) 介绍了 Open Food Facts 公益组织利用 LLM 解决识别食品成分时遇到的问题。文章写得非常精彩，其中关于问题的具体分析、智能算法的评估指标的定义以及各种开源工具的合理应用等部分非常值得参考。

下面列出这篇文章中我第一次遇到的新鲜技术和工具：

1. 拼写检查算法，一个简单的方法可以参考[[https://norvig.com/spell-correct.html][这里]]。
2. 序列对齐算法 (Sequence Alignment) ，主要用在 bio-informatic 中，文中利用该方法来定义评估指标。
3. Argilla，一个开源的 NLP 标记工具。
4. 开源的 LLMs ：T5 family， Llama，Mistral 等。
5. Metaflow，一个开发、扩展和部署 AI 系统的开源平台。
6. Comet，一个从模型训练到生产的全生命管理工具，提供的训练状态监测，实验追踪等功能。
7. 各种用于训练和部署 LLMs 的云平台，如 Amazon SageMaker 等。
8. vLLM，加速 LLM 推断的 Python 库。

该作者在其另一篇文章 ([[https://medium.com/@jeremyarancio/duckdb-open-food-facts-the-largest-open-food-database-in-the-palm-of-your-hand-0d4ab30d0701][DuckDB & Open Food Facts]]) 中介绍了如何使用 DuckDB 来分析 Open Food Facts Dataset ，也是很有意思。DuckDB 是分析中型数据集 (1G - 100G) 最方便的工具，在本地就可以轻松完成。


** TTY Demystified

关于 TTY 的资料很少，再加上历史因素，让其显得古老和神秘。这篇文章，[[https://www.linusakesson.net/programming/tty/][The TTY demystified]]，揭开了 TTY 神秘的面纱，非常值得阅读。


** Free-threaded CPython (3.13)

CPython 3.13 版本迎来重大实验性更新，现在 python 代码可以越过 GIL ，跑在 free-threaded mode 中，实现真正的多线程。

GIL 是 python 解释器的全局锁，阻止多个 python 线程同时执行 python 字节码。起初这样设计主要是为了简化内存管理以及和 C API 的交互。但是这也让其无法充分有效的利用现代多核处理器。


** FeedSpot

FeedSpot 是一个内容发现和聚合平台，用户可以订阅其服务获得个性化的内容（博客，播客等）推荐。

对于还在使用 RSS 获取信息的朋友是一个巨大的福音，上面有很多优质 RSS Feeds 推荐。下面是我搜索的一些：

- [[https://rss.feedspot.com/ai_rss_feeds/][Top 100 Artificial Intelligence RSS Feeds]]
- [[https://rss.feedspot.com/machine_learning_rss_feeds/][Top 90 Machine Learning RSS Feeds]]
- [[https://rss.feedspot.com/linux_rss_feeds/][Top 90 Linux RSS Feeds]]


** Py-Googletrans

免费无限制的非官方 Google translate API 。

作者在其 README 里直言该库采用了一些逆向方法，所以可能后面会被 Google 封锁。


** CI/CD for Python with Github Actions

CI/CD 已经成为现代软件质量保障的基础设施， Real Python 上的这篇[[https://realpython.com/github-actions-python/][文章]]详细的讲解了其使用方法。


** DuckDB

DuckDB 是一个面向数据分析场景的嵌入式数据库，可以看作是 AP 版本的 SQLite 。


** Parquet File Format

Apache Parquet 是专门为大数据处理设计优化的列存储文件格式，被许多大数据处理框架使用。

R 语言的 nanoparquet 包可用于读写 parquet 文件格式。
