bname: org-denotes-publish

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: purcell/setup-emacs@master
        with:
          version: 28.2
      - uses: actions/checkout@v3
      - run: |
          cd scaffold
          make clean
          make

      - uses: actions/configure-pages@v3
      - uses: actions/upload-pages-artifact@v1
        with:
          path: './public_html'
      - uses: actions/deploy-pages@v1
