name: org-denotes-publish

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: purcell/setup-emacs@master
        with:
          version: 28.2
      - uses: actions/checkout@v3
      - run: |
          cd scaffold
          make clean
          make
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./scaffold/public_html
