name: org-denotes-publish

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: purcell/setup-emacs@master
        with:
          version: 28.2
      - uses: actions/checkout@v3
      - run: |
          cd scaffold
          make clean
          make
      - uses: actions/configure-pages@v3
      - uses: actions/upload-pages-artifact@v1
        with:
          path: './scaffold/public_html'
      - uses: actions/deploy-pages@v1
